# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import provaldo_pb2 as provaldo__pb2


class ValidadorStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Validar = channel.unary_unary(
                '/provaldo.Validador/Validar',
                request_serializer=provaldo__pb2.ProvaldoRequest.SerializeToString,
                response_deserializer=provaldo__pb2.ProvaldoReply.FromString,
                )


class ValidadorServicer(object):
    """The greeting service definition.
    """

    def Validar(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ValidadorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Validar': grpc.unary_unary_rpc_method_handler(
                    servicer.Validar,
                    request_deserializer=provaldo__pb2.ProvaldoRequest.FromString,
                    response_serializer=provaldo__pb2.ProvaldoReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'provaldo.Validador', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Validador(object):
    """The greeting service definition.
    """

    @staticmethod
    def Validar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/provaldo.Validador/Validar',
            provaldo__pb2.ProvaldoRequest.SerializeToString,
            provaldo__pb2.ProvaldoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
