# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: provaldo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprovaldo.proto\x12\x08provaldo\"-\n\x0fProvaldoRequest\x12\x0c\n\x04\x64ocn\x18\x01 \x01(\t\x12\x0c\n\x04\x64oct\x18\x02 \x01(\x05\"G\n\rProvaldoReply\x12\x0c\n\x04\x64tvd\x18\x01 \x01(\t\x12\x0c\n\x04\x64ocn\x18\x02 \x01(\t\x12\x0c\n\x04\x64oct\x18\x03 \x01(\x05\x12\x0c\n\x04\x64ocv\x18\x04 \x01(\x05\x32L\n\tValidador\x12?\n\x07Validar\x12\x19.provaldo.ProvaldoRequest\x1a\x17.provaldo.ProvaldoReply\"\x00\x42,\n\x18\x62r.edu.ifsp.pep.provaldoB\x08ProvaldoP\x01\xa2\x02\x03PVDb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'provaldo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030br.edu.ifsp.pep.provaldoB\010ProvaldoP\001\242\002\003PVD'
  _globals['_PROVALDOREQUEST']._serialized_start=28
  _globals['_PROVALDOREQUEST']._serialized_end=73
  _globals['_PROVALDOREPLY']._serialized_start=75
  _globals['_PROVALDOREPLY']._serialized_end=146
  _globals['_VALIDADOR']._serialized_start=148
  _globals['_VALIDADOR']._serialized_end=224
# @@protoc_insertion_point(module_scope)
